; Disassembly of "Mario's Picross (USA, Europe) (SGB Enhanced).gb"
; This file was created with:
; mgbdis v3.0 - Game Boy ROM disassembler by Matt Currie and contributors.
; https://github.com/mattcurrie/mgbdis

DEF ActiveROMBank EQU $c312
DEF RequestedROMBank EQU $c314
DEF GameMode_Current EQU $d634
DEF GameState_Current EQU $d635
DEF CurrentGridSize EQU $d800
DEF LevelSelectColumn EQU $f635
DEF LevelSelectRow EQU $f636
